local I2ScrBuilder = {}

function I2ScrBuilder:Build(I2ScrEOFLocation: Instance)

	-- Time Taken: 0.010849600000028659s, Name: KHLibUI, Class: ScreenGui, Variable: I2ScrEOFKHLibUIEOF5672id2561 
	local I2ScrEOFKHLibUIEOF5672id2561 = Instance.new("ScreenGui", I2ScrEOFLocation)
	I2ScrEOFKHLibUIEOF5672id2561.Name = "KHLibUI"
	I2ScrEOFKHLibUIEOF5672id2561.ZIndexBehavior = Enum.ZIndexBehavior.Sibling

	-- Time Taken: 0.10809649999998783s, Name: Main, Class: Frame, Variable: I2ScrEOFMainEOF4084id4498 
	local I2ScrEOFMainEOF4084id4498 = Instance.new("Frame", I2ScrEOFKHLibUIEOF5672id2561)
	I2ScrEOFMainEOF4084id4498.AnchorPoint = Vector2.new(0.5, 0.5)
	I2ScrEOFMainEOF4084id4498.BackgroundColor3 = Color3.new(0.176471, 0.176471, 0.176471)
	I2ScrEOFMainEOF4084id4498.BackgroundTransparency = 0.5
	I2ScrEOFMainEOF4084id4498.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFMainEOF4084id4498.BorderSizePixel = 0
	I2ScrEOFMainEOF4084id4498.Name = "Main"
	I2ScrEOFMainEOF4084id4498.Position = UDim2.new(0.5, 0, 0.5, 0)
	I2ScrEOFMainEOF4084id4498.Size = UDim2.new(0.351999998, 0, 0.416999996, 0)
	I2ScrEOFMainEOF4084id4498.Visible = false

	-- Time Taken: 0.0161527999999862s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF3396id5008 
	local I2ScrEOFUICornerEOF3396id5008 = Instance.new("UICorner", I2ScrEOFMainEOF4084id4498)
	I2ScrEOFUICornerEOF3396id5008.CornerRadius = UDim.new(0.0500000007, 0)

	-- Time Taken: 0.05580689999987953s, Name: TabArea, Class: Frame, Variable: I2ScrEOFTabAreaEOF2709id7065 
	local I2ScrEOFTabAreaEOF2709id7065 = Instance.new("Frame", I2ScrEOFMainEOF4084id4498)
	I2ScrEOFTabAreaEOF2709id7065.BackgroundColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTabAreaEOF2709id7065.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTabAreaEOF2709id7065.BorderSizePixel = 0
	I2ScrEOFTabAreaEOF2709id7065.Name = "TabArea"
	I2ScrEOFTabAreaEOF2709id7065.Position = UDim2.new(0.333333343, 0, 0, 0)
	I2ScrEOFTabAreaEOF2709id7065.Size = UDim2.new(0.666666687, 0, 1, 0)

	-- Time Taken: 0.014977299999941351s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF7083id5579 
	local I2ScrEOFUICornerEOF7083id5579 = Instance.new("UICorner", I2ScrEOFTabAreaEOF2709id7065)
	I2ScrEOFUICornerEOF7083id5579.CornerRadius = UDim.new(0.0500000007, 0)

	-- Time Taken: 0.004048900000043432s, Name: Borders, Class: Folder, Variable: I2ScrEOFBordersEOF5720id7783 
	local I2ScrEOFBordersEOF5720id7783 = Instance.new("Folder", I2ScrEOFTabAreaEOF2709id7065)
	I2ScrEOFBordersEOF5720id7783.Name = "Borders"

	-- Time Taken: 0.06244650000007823s, Name: TopLeftCornerBorder, Class: Frame, Variable: I2ScrEOFTopLeftCornerBorderEOF3632id7846 
	local I2ScrEOFTopLeftCornerBorderEOF3632id7846 = Instance.new("Frame", I2ScrEOFBordersEOF5720id7783)
	I2ScrEOFTopLeftCornerBorderEOF3632id7846.BackgroundColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTopLeftCornerBorderEOF3632id7846.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTopLeftCornerBorderEOF3632id7846.BorderSizePixel = 0
	I2ScrEOFTopLeftCornerBorderEOF3632id7846.Name = "TopLeftCornerBorder"
	I2ScrEOFTopLeftCornerBorderEOF3632id7846.Size = UDim2.new(0.0500000007, 0, 0.0500000007, 0)

	-- Time Taken: 0.08256760000017493s, Name: BottomLeftCornerBorder, Class: Frame, Variable: I2ScrEOFBottomLeftCornerBorderEOF7097id1231 
	local I2ScrEOFBottomLeftCornerBorderEOF7097id1231 = Instance.new("Frame", I2ScrEOFBordersEOF5720id7783)
	I2ScrEOFBottomLeftCornerBorderEOF7097id1231.BackgroundColor3 = Color3.new(0, 0, 0)
	I2ScrEOFBottomLeftCornerBorderEOF7097id1231.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFBottomLeftCornerBorderEOF7097id1231.BorderSizePixel = 0
	I2ScrEOFBottomLeftCornerBorderEOF7097id1231.Name = "BottomLeftCornerBorder"
	I2ScrEOFBottomLeftCornerBorderEOF7097id1231.Position = UDim2.new(0, 0, 0.949999988, 0)
	I2ScrEOFBottomLeftCornerBorderEOF7097id1231.Size = UDim2.new(0.0500000007, 0, 0.0500000007, 0)

	-- Time Taken: 0.07157629999994697s, Name: Frame, Class: Frame, Variable: I2ScrEOFFrameEOF5378id6310 
	local I2ScrEOFFrameEOF5378id6310 = Instance.new("Frame", I2ScrEOFBordersEOF5720id7783)
	I2ScrEOFFrameEOF5378id6310.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFFrameEOF5378id6310.BorderColor3 = Color3.new(0.176471, 0.176471, 0.176471)
	I2ScrEOFFrameEOF5378id6310.BorderSizePixel = 0
	I2ScrEOFFrameEOF5378id6310.Position = UDim2.new(0, 0, 0.112999998, 0)
	I2ScrEOFFrameEOF5378id6310.Size = UDim2.new(1, 0, 0.00666666683, 0)

	-- Time Taken: 0.07328430000006847s, Name: TabInfoArea, Class: Frame, Variable: I2ScrEOFTabInfoAreaEOF1228id5725 
	local I2ScrEOFTabInfoAreaEOF1228id5725 = Instance.new("Frame", I2ScrEOFTabAreaEOF2709id7065)
	I2ScrEOFTabInfoAreaEOF1228id5725.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFTabInfoAreaEOF1228id5725.BackgroundTransparency = 1
	I2ScrEOFTabInfoAreaEOF1228id5725.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTabInfoAreaEOF1228id5725.BorderSizePixel = 0
	I2ScrEOFTabInfoAreaEOF1228id5725.Name = "TabInfoArea"
	I2ScrEOFTabInfoAreaEOF1228id5725.Size = UDim2.new(1, 0, 0.109999999, 0)

	-- Time Taken: 0.08388349999995626s, Name: MenuOptions, Class: Frame, Variable: I2ScrEOFMenuOptionsEOF5011id4286 
	local I2ScrEOFMenuOptionsEOF5011id4286 = Instance.new("Frame", I2ScrEOFTabInfoAreaEOF1228id5725)
	I2ScrEOFMenuOptionsEOF5011id4286.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFMenuOptionsEOF5011id4286.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFMenuOptionsEOF5011id4286.BorderSizePixel = 0
	I2ScrEOFMenuOptionsEOF5011id4286.Name = "MenuOptions"
	I2ScrEOFMenuOptionsEOF5011id4286.Position = UDim2.new(0.836666644, 0, 0.181818187, 0)
	I2ScrEOFMenuOptionsEOF5011id4286.Size = UDim2.new(0.13333334, 0, 0.606060624, 0)

	-- Time Taken: 0.015033799999969233s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF2822id1503 
	local I2ScrEOFUICornerEOF2822id1503 = Instance.new("UICorner", I2ScrEOFMenuOptionsEOF5011id4286)
	I2ScrEOFUICornerEOF2822id1503.CornerRadius = UDim.new(0.400000006, 0)

	-- Time Taken: 0.19760829999995622s, Name: Minimize, Class: TextButton, Variable: I2ScrEOFMinimizeEOF3724id9990 
	local I2ScrEOFMinimizeEOF3724id9990 = Instance.new("TextButton", I2ScrEOFMenuOptionsEOF5011id4286)
	I2ScrEOFMinimizeEOF3724id9990.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFMinimizeEOF3724id9990.BackgroundTransparency = 1
	I2ScrEOFMinimizeEOF3724id9990.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFMinimizeEOF3724id9990.BorderSizePixel = 0
	I2ScrEOFMinimizeEOF3724id9990.Name = "Minimize"
	I2ScrEOFMinimizeEOF3724id9990.Position = UDim2.new(0.100000001, 0, 0.150000006, 0)
	I2ScrEOFMinimizeEOF3724id9990.Size = UDim2.new(0.375, 0, 0.75, 0)
	I2ScrEOFMinimizeEOF3724id9990.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFMinimizeEOF3724id9990.Text = "–"
	I2ScrEOFMinimizeEOF3724id9990.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFMinimizeEOF3724id9990.TextScaled = true
	I2ScrEOFMinimizeEOF3724id9990.TextSize = 14
	I2ScrEOFMinimizeEOF3724id9990.TextWrapped = true

	-- Time Taken: 0.16182890000027328s, Name: Destroy, Class: TextButton, Variable: I2ScrEOFDestroyEOF4038id9786 
	local I2ScrEOFDestroyEOF4038id9786 = Instance.new("TextButton", I2ScrEOFMenuOptionsEOF5011id4286)
	I2ScrEOFDestroyEOF4038id9786.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDestroyEOF4038id9786.BackgroundTransparency = 1
	I2ScrEOFDestroyEOF4038id9786.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFDestroyEOF4038id9786.BorderSizePixel = 0
	I2ScrEOFDestroyEOF4038id9786.Name = "Destroy"
	I2ScrEOFDestroyEOF4038id9786.Position = UDim2.new(0.5, 0, 0.150000006, 0)
	I2ScrEOFDestroyEOF4038id9786.Size = UDim2.new(0.375, 0, 0.75, 0)
	I2ScrEOFDestroyEOF4038id9786.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFDestroyEOF4038id9786.Text = "X"
	I2ScrEOFDestroyEOF4038id9786.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDestroyEOF4038id9786.TextScaled = true
	I2ScrEOFDestroyEOF4038id9786.TextSize = 14
	I2ScrEOFDestroyEOF4038id9786.TextWrapped = true

	-- Time Taken: 0.22196499999995467s, Name: TabTitle, Class: TextLabel, Variable: I2ScrEOFTabTitleEOF9542id7518 
	local I2ScrEOFTabTitleEOF9542id7518 = Instance.new("TextLabel", I2ScrEOFTabInfoAreaEOF1228id5725)
	I2ScrEOFTabTitleEOF9542id7518.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFTabTitleEOF9542id7518.BackgroundTransparency = 1
	I2ScrEOFTabTitleEOF9542id7518.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTabTitleEOF9542id7518.BorderSizePixel = 0
	I2ScrEOFTabTitleEOF9542id7518.Name = "TabTitle"
	I2ScrEOFTabTitleEOF9542id7518.Position = UDim2.new(0.0233151298, 0, 0.272679955, 0)
	I2ScrEOFTabTitleEOF9542id7518.Size = UDim2.new(0.757000029, 0, 0.454515159, 0)
	I2ScrEOFTabTitleEOF9542id7518.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFTabTitleEOF9542id7518.RichText = true
	I2ScrEOFTabTitleEOF9542id7518.Text = "Koala Hacks Template Tab"
	I2ScrEOFTabTitleEOF9542id7518.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFTabTitleEOF9542id7518.TextScaled = true
	I2ScrEOFTabTitleEOF9542id7518.TextSize = 14
	I2ScrEOFTabTitleEOF9542id7518.TextWrapped = true
	I2ScrEOFTabTitleEOF9542id7518.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.0028058999999984735s, Name: Tabs, Class: Folder, Variable: I2ScrEOFTabsEOF8893id2177 
	local I2ScrEOFTabsEOF8893id2177 = Instance.new("Folder", I2ScrEOFTabAreaEOF2709id7065)
	I2ScrEOFTabsEOF8893id2177.Name = "Tabs"

	-- Time Taken: 0.1992449999999053s, Name: KH_TemplateTab, Class: ScrollingFrame, Variable: I2ScrEOFKH_TemplateTabEOF6930id3449 
	local I2ScrEOFKH_TemplateTabEOF6930id3449 = Instance.new("ScrollingFrame", I2ScrEOFTabsEOF8893id2177)
	I2ScrEOFKH_TemplateTabEOF6930id3449.Active = true
	I2ScrEOFKH_TemplateTabEOF6930id3449.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFKH_TemplateTabEOF6930id3449.BackgroundTransparency = 1
	I2ScrEOFKH_TemplateTabEOF6930id3449.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFKH_TemplateTabEOF6930id3449.BorderSizePixel = 0
	I2ScrEOFKH_TemplateTabEOF6930id3449.Name = "KH_TemplateTab"
	I2ScrEOFKH_TemplateTabEOF6930id3449.Position = UDim2.new(0, 0, 0.116666667, 0)
	I2ScrEOFKH_TemplateTabEOF6930id3449.Size = UDim2.new(1, 0, 0.883333325, 0)
	I2ScrEOFKH_TemplateTabEOF6930id3449.Visible = false
	I2ScrEOFKH_TemplateTabEOF6930id3449.BottomImage = "http://www.roblox.com/asset/?id=10995799876"
	I2ScrEOFKH_TemplateTabEOF6930id3449.CanvasSize = UDim2.new(0, 0, 3, 0)
	I2ScrEOFKH_TemplateTabEOF6930id3449.MidImage = "http://www.roblox.com/asset/?id=10995799876"
	I2ScrEOFKH_TemplateTabEOF6930id3449.ScrollBarImageColor3 = Color3.new(0.490196, 0.490196, 0.490196)
	I2ScrEOFKH_TemplateTabEOF6930id3449.ScrollBarThickness = 3
	I2ScrEOFKH_TemplateTabEOF6930id3449.TopImage = "http://www.roblox.com/asset/?id=10995799876"

	-- Time Taken: 0.03726100000005772s, Name: UIListLayout, Class: UIListLayout, Variable: I2ScrEOFUIListLayoutEOF412id7465 
	local I2ScrEOFUIListLayoutEOF412id7465 = Instance.new("UIListLayout", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFUIListLayoutEOF412id7465.Padding = UDim.new(0.0111111114, 0)
	I2ScrEOFUIListLayoutEOF412id7465.SortOrder = Enum.SortOrder.LayoutOrder
	I2ScrEOFUIListLayoutEOF412id7465.HorizontalAlignment = Enum.HorizontalAlignment.Center

	-- Time Taken: 0.039247700000146324s, Name: Padding, Class: Frame, Variable: I2ScrEOFPaddingEOF1075id9400 
	local I2ScrEOFPaddingEOF1075id9400 = Instance.new("Frame", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFPaddingEOF1075id9400.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFPaddingEOF1075id9400.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFPaddingEOF1075id9400.BorderSizePixel = 0
	I2ScrEOFPaddingEOF1075id9400.Name = "Padding"

	-- Time Taken: 0.07243669999991198s, Name: Action_Activate, Class: Frame, Variable: I2ScrEOFAction_ActivateEOF9827id6043 
	local I2ScrEOFAction_ActivateEOF9827id6043 = Instance.new("Frame", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFAction_ActivateEOF9827id6043.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFAction_ActivateEOF9827id6043.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFAction_ActivateEOF9827id6043.BorderSizePixel = 0
	I2ScrEOFAction_ActivateEOF9827id6043.Name = "Action_Activate"
	I2ScrEOFAction_ActivateEOF9827id6043.Position = UDim2.new(0.333333343, 0, 0.177358493, 0)
	I2ScrEOFAction_ActivateEOF9827id6043.Size = UDim2.new(0.949999988, 0, 0.0333333351, 0)

	-- Time Taken: 0.012453899999968598s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF332id8215 
	local I2ScrEOFUICornerEOF332id8215 = Instance.new("UICorner", I2ScrEOFAction_ActivateEOF9827id6043)
	I2ScrEOFUICornerEOF332id8215.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.10009470000022702s, Name: Icon, Class: ImageLabel, Variable: I2ScrEOFIconEOF7499id3084 
	local I2ScrEOFIconEOF7499id3084 = Instance.new("ImageLabel", I2ScrEOFAction_ActivateEOF9827id6043)
	I2ScrEOFIconEOF7499id3084.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFIconEOF7499id3084.BackgroundTransparency = 1
	I2ScrEOFIconEOF7499id3084.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFIconEOF7499id3084.BorderSizePixel = 0
	I2ScrEOFIconEOF7499id3084.Name = "Icon"
	I2ScrEOFIconEOF7499id3084.Size = UDim2.new(0.105263159, 0, 0.99999994, 0)
	I2ScrEOFIconEOF7499id3084.Image = "rbxassetid://18352620579"

	-- Time Taken: 0.22477949999995417s, Name: Description, Class: TextLabel, Variable: I2ScrEOFDescriptionEOF7388id9767 
	local I2ScrEOFDescriptionEOF7388id9767 = Instance.new("TextLabel", I2ScrEOFAction_ActivateEOF9827id6043)
	I2ScrEOFDescriptionEOF7388id9767.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFDescriptionEOF7388id9767.BackgroundTransparency = 1
	I2ScrEOFDescriptionEOF7388id9767.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFDescriptionEOF7388id9767.BorderSizePixel = 0
	I2ScrEOFDescriptionEOF7388id9767.Name = "Description"
	I2ScrEOFDescriptionEOF7388id9767.Position = UDim2.new(0.129824564, 0, 0.166666657, 0)
	I2ScrEOFDescriptionEOF7388id9767.Size = UDim2.new(0.870175421, 0, 0.666666627, 0)
	I2ScrEOFDescriptionEOF7388id9767.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFDescriptionEOF7388id9767.Text = "Activate"
	I2ScrEOFDescriptionEOF7388id9767.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDescriptionEOF7388id9767.TextScaled = true
	I2ScrEOFDescriptionEOF7388id9767.TextSize = 14
	I2ScrEOFDescriptionEOF7388id9767.TextStrokeTransparency = 0
	I2ScrEOFDescriptionEOF7388id9767.TextWrapped = true
	I2ScrEOFDescriptionEOF7388id9767.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.13691670000002887s, Name: Activate, Class: TextButton, Variable: I2ScrEOFActivateEOF7835id3930 
	local I2ScrEOFActivateEOF7835id3930 = Instance.new("TextButton", I2ScrEOFAction_ActivateEOF9827id6043)
	I2ScrEOFActivateEOF7835id3930.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFActivateEOF7835id3930.BackgroundTransparency = 1
	I2ScrEOFActivateEOF7835id3930.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFActivateEOF7835id3930.BorderSizePixel = 0
	I2ScrEOFActivateEOF7835id3930.Name = "Activate"
	I2ScrEOFActivateEOF7835id3930.Size = UDim2.new(1, 0, 1, 0)
	I2ScrEOFActivateEOF7835id3930.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFActivateEOF7835id3930.TextColor3 = Color3.new(0, 0, 0)
	I2ScrEOFActivateEOF7835id3930.TextSize = 14
	I2ScrEOFActivateEOF7835id3930.TextTransparency = 1

	-- Time Taken: 0.005730200000016339s, Name: Config, Class: Folder, Variable: I2ScrEOFConfigEOF6330id4542 
	local I2ScrEOFConfigEOF6330id4542 = Instance.new("Folder", I2ScrEOFAction_ActivateEOF9827id6043)
	I2ScrEOFConfigEOF6330id4542.Name = "Config"

	-- Time Taken: 0.014237200000025041s, Name: #ActActivate, Class: StringValue, Variable: I2ScrEOF_ActActivateEOF9589id2224 
	local I2ScrEOF_ActActivateEOF9589id2224 = Instance.new("StringValue", I2ScrEOFConfigEOF6330id4542)
	I2ScrEOF_ActActivateEOF9589id2224.Name = "#ActActivate"

	-- Time Taken: 0.014284299999985706s, Name: Config, Class: Folder, Variable: I2ScrEOFConfigEOF9864id2364 
	local I2ScrEOFConfigEOF9864id2364 = Instance.new("Folder", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFConfigEOF9864id2364.Name = "Config"

	-- Time Taken: 0.08482900000001337s, Name: Action_ColorPick, Class: Frame, Variable: I2ScrEOFAction_ColorPickEOF6192id8377 
	local I2ScrEOFAction_ColorPickEOF6192id8377 = Instance.new("Frame", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFAction_ColorPickEOF6192id8377.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFAction_ColorPickEOF6192id8377.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFAction_ColorPickEOF6192id8377.BorderSizePixel = 0
	I2ScrEOFAction_ColorPickEOF6192id8377.Name = "Action_ColorPick"
	I2ScrEOFAction_ColorPickEOF6192id8377.Position = UDim2.new(0.333333343, 0, 0.177358493, 0)
	I2ScrEOFAction_ColorPickEOF6192id8377.Size = UDim2.new(0.949999988, 0, 0.0333333351, 0)

	-- Time Taken: 0.021272599999974773s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF7381id1452 
	local I2ScrEOFUICornerEOF7381id1452 = Instance.new("UICorner", I2ScrEOFAction_ColorPickEOF6192id8377)
	I2ScrEOFUICornerEOF7381id1452.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.21802199999990535s, Name: Description, Class: TextLabel, Variable: I2ScrEOFDescriptionEOF6604id3257 
	local I2ScrEOFDescriptionEOF6604id3257 = Instance.new("TextLabel", I2ScrEOFAction_ColorPickEOF6192id8377)
	I2ScrEOFDescriptionEOF6604id3257.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFDescriptionEOF6604id3257.BackgroundTransparency = 1
	I2ScrEOFDescriptionEOF6604id3257.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFDescriptionEOF6604id3257.BorderSizePixel = 0
	I2ScrEOFDescriptionEOF6604id3257.Name = "Description"
	I2ScrEOFDescriptionEOF6604id3257.Position = UDim2.new(0.129824489, 0, 0.166666314, 0)
	I2ScrEOFDescriptionEOF6604id3257.Size = UDim2.new(0.870175421, 0, 0.666666627, 0)
	I2ScrEOFDescriptionEOF6604id3257.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFDescriptionEOF6604id3257.Text = "Color Pick"
	I2ScrEOFDescriptionEOF6604id3257.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDescriptionEOF6604id3257.TextScaled = true
	I2ScrEOFDescriptionEOF6604id3257.TextSize = 14
	I2ScrEOFDescriptionEOF6604id3257.TextStrokeTransparency = 0
	I2ScrEOFDescriptionEOF6604id3257.TextWrapped = true
	I2ScrEOFDescriptionEOF6604id3257.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.14396000000010645s, Name: Activate, Class: TextButton, Variable: I2ScrEOFActivateEOF7067id7329 
	local I2ScrEOFActivateEOF7067id7329 = Instance.new("TextButton", I2ScrEOFAction_ColorPickEOF6192id8377)
	I2ScrEOFActivateEOF7067id7329.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFActivateEOF7067id7329.BackgroundTransparency = 1
	I2ScrEOFActivateEOF7067id7329.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFActivateEOF7067id7329.BorderSizePixel = 0
	I2ScrEOFActivateEOF7067id7329.Name = "Activate"
	I2ScrEOFActivateEOF7067id7329.Size = UDim2.new(1, 0, 1, 0)
	I2ScrEOFActivateEOF7067id7329.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFActivateEOF7067id7329.TextColor3 = Color3.new(0, 0, 0)
	I2ScrEOFActivateEOF7067id7329.TextSize = 14
	I2ScrEOFActivateEOF7067id7329.TextTransparency = 1

	-- Time Taken: 0.005325100000050043s, Name: Config, Class: Folder, Variable: I2ScrEOFConfigEOF1436id8968 
	local I2ScrEOFConfigEOF1436id8968 = Instance.new("Folder", I2ScrEOFAction_ColorPickEOF6192id8377)
	I2ScrEOFConfigEOF1436id8968.Name = "Config"

	-- Time Taken: 0.006184400000051937s, Name: #ActColorPick, Class: StringValue, Variable: I2ScrEOF_ActColorPickEOF1103id9799 
	local I2ScrEOF_ActColorPickEOF1103id9799 = Instance.new("StringValue", I2ScrEOFConfigEOF1436id8968)
	I2ScrEOF_ActColorPickEOF1103id9799.Name = "#ActColorPick"

	-- Time Taken: 0.03304620000005798s, Name: Color, Class: Color3Value, Variable: I2ScrEOFColorEOF3984id7182 
	local I2ScrEOFColorEOF3984id7182 = Instance.new("Color3Value", I2ScrEOFConfigEOF1436id8968)
	I2ScrEOFColorEOF3984id7182.Name = "Color"
	I2ScrEOFColorEOF3984id7182.Value = Color3.new(1, 1, 1)

	-- Time Taken: 0.10624630000017987s, Name: ColorIcon, Class: ImageLabel, Variable: I2ScrEOFColorIconEOF1479id6090 
	local I2ScrEOFColorIconEOF1479id6090 = Instance.new("ImageLabel", I2ScrEOFAction_ColorPickEOF6192id8377)
	I2ScrEOFColorIconEOF1479id6090.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFColorIconEOF1479id6090.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFColorIconEOF1479id6090.BorderSizePixel = 0
	I2ScrEOFColorIconEOF1479id6090.Name = "ColorIcon"
	I2ScrEOFColorIconEOF1479id6090.Position = UDim2.new(0.0250000004, 0, 0.133000001, 0)
	I2ScrEOFColorIconEOF1479id6090.Size = UDim2.new(0.0700000003, 0, 0.666000009, 0)
	I2ScrEOFColorIconEOF1479id6090.Image = "rbxassetid://105955025341798"

	-- Time Taken: 0.017397099999925558s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF3535id96 
	local I2ScrEOFUICornerEOF3535id96 = Instance.new("UICorner", I2ScrEOFColorIconEOF1479id6090)
	I2ScrEOFUICornerEOF3535id96.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.07441560000006575s, Name: Action_Toggle, Class: Frame, Variable: I2ScrEOFAction_ToggleEOF7250id3497 
	local I2ScrEOFAction_ToggleEOF7250id3497 = Instance.new("Frame", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFAction_ToggleEOF7250id3497.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFAction_ToggleEOF7250id3497.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFAction_ToggleEOF7250id3497.BorderSizePixel = 0
	I2ScrEOFAction_ToggleEOF7250id3497.Name = "Action_Toggle"
	I2ScrEOFAction_ToggleEOF7250id3497.Position = UDim2.new(0.333333343, 0, 0.177358493, 0)
	I2ScrEOFAction_ToggleEOF7250id3497.Size = UDim2.new(0.949999988, 0, 0.0333333351, 0)

	-- Time Taken: 0.019057999999972708s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF7137id3200 
	local I2ScrEOFUICornerEOF7137id3200 = Instance.new("UICorner", I2ScrEOFAction_ToggleEOF7250id3497)
	I2ScrEOFUICornerEOF7137id3200.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.07747819999974581s, Name: ToggleArea, Class: Frame, Variable: I2ScrEOFToggleAreaEOF4884id6295 
	local I2ScrEOFToggleAreaEOF4884id6295 = Instance.new("Frame", I2ScrEOFAction_ToggleEOF7250id3497)
	I2ScrEOFToggleAreaEOF4884id6295.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFToggleAreaEOF4884id6295.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFToggleAreaEOF4884id6295.BorderSizePixel = 0
	I2ScrEOFToggleAreaEOF4884id6295.Name = "ToggleArea"
	I2ScrEOFToggleAreaEOF4884id6295.Position = UDim2.new(0.0175575763, 0, 0.133437574, 0)
	I2ScrEOFToggleAreaEOF4884id6295.Size = UDim2.new(0.140350878, 0, 0.666666627, 0)

	-- Time Taken: 0.01686819999997624s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF336id7236 
	local I2ScrEOFUICornerEOF336id7236 = Instance.new("UICorner", I2ScrEOFToggleAreaEOF4884id6295)
	I2ScrEOFUICornerEOF336id7236.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.11535700000001725s, Name: ToggleIcon, Class: ImageLabel, Variable: I2ScrEOFToggleIconEOF7335id4983 
	local I2ScrEOFToggleIconEOF7335id4983 = Instance.new("ImageLabel", I2ScrEOFToggleAreaEOF4884id6295)
	I2ScrEOFToggleIconEOF7335id4983.BackgroundColor3 = Color3.new(1, 0.34902, 0.34902)
	I2ScrEOFToggleIconEOF7335id4983.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFToggleIconEOF7335id4983.BorderSizePixel = 0
	I2ScrEOFToggleIconEOF7335id4983.Name = "ToggleIcon"
	I2ScrEOFToggleIconEOF7335id4983.Position = UDim2.new(0.0500000007, 0, 0, 0)
	I2ScrEOFToggleIconEOF7335id4983.Size = UDim2.new(0.5, 0, 1, 0)
	I2ScrEOFToggleIconEOF7335id4983.Image = "rbxassetid://18352620579"

	-- Time Taken: 0.02137290000007397s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF5233id5405 
	local I2ScrEOFUICornerEOF5233id5405 = Instance.new("UICorner", I2ScrEOFToggleIconEOF7335id4983)
	I2ScrEOFUICornerEOF5233id5405.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.2568258999998534s, Name: Description, Class: TextLabel, Variable: I2ScrEOFDescriptionEOF5952id8803 
	local I2ScrEOFDescriptionEOF5952id8803 = Instance.new("TextLabel", I2ScrEOFAction_ToggleEOF7250id3497)
	I2ScrEOFDescriptionEOF5952id8803.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFDescriptionEOF5952id8803.BackgroundTransparency = 1
	I2ScrEOFDescriptionEOF5952id8803.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFDescriptionEOF5952id8803.BorderSizePixel = 0
	I2ScrEOFDescriptionEOF5952id8803.Name = "Description"
	I2ScrEOFDescriptionEOF5952id8803.Position = UDim2.new(0.180105492, 0, 0.166666657, 0)
	I2ScrEOFDescriptionEOF5952id8803.Size = UDim2.new(0.817543864, 0, 0.666666627, 0)
	I2ScrEOFDescriptionEOF5952id8803.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFDescriptionEOF5952id8803.Text = "Toggle"
	I2ScrEOFDescriptionEOF5952id8803.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDescriptionEOF5952id8803.TextScaled = true
	I2ScrEOFDescriptionEOF5952id8803.TextSize = 14
	I2ScrEOFDescriptionEOF5952id8803.TextStrokeTransparency = 0
	I2ScrEOFDescriptionEOF5952id8803.TextWrapped = true
	I2ScrEOFDescriptionEOF5952id8803.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.15590229999986605s, Name: Activate, Class: TextButton, Variable: I2ScrEOFActivateEOF6915id5483 
	local I2ScrEOFActivateEOF6915id5483 = Instance.new("TextButton", I2ScrEOFAction_ToggleEOF7250id3497)
	I2ScrEOFActivateEOF6915id5483.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFActivateEOF6915id5483.BackgroundTransparency = 1
	I2ScrEOFActivateEOF6915id5483.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFActivateEOF6915id5483.BorderSizePixel = 0
	I2ScrEOFActivateEOF6915id5483.Name = "Activate"
	I2ScrEOFActivateEOF6915id5483.Size = UDim2.new(1, 0, 1, 0)
	I2ScrEOFActivateEOF6915id5483.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFActivateEOF6915id5483.TextColor3 = Color3.new(0, 0, 0)
	I2ScrEOFActivateEOF6915id5483.TextSize = 14
	I2ScrEOFActivateEOF6915id5483.TextTransparency = 1

	-- Time Taken: 0.011257899999918664s, Name: Config, Class: Folder, Variable: I2ScrEOFConfigEOF6051id1965 
	local I2ScrEOFConfigEOF6051id1965 = Instance.new("Folder", I2ScrEOFAction_ToggleEOF7250id3497)
	I2ScrEOFConfigEOF6051id1965.Name = "Config"

	-- Time Taken: 0.015322600000104103s, Name: #ActToggle, Class: StringValue, Variable: I2ScrEOF_ActToggleEOF5414id5920 
	local I2ScrEOF_ActToggleEOF5414id5920 = Instance.new("StringValue", I2ScrEOFConfigEOF6051id1965)
	I2ScrEOF_ActToggleEOF5414id5920.Name = "#ActToggle"

	-- Time Taken: 0.008647600000017519s, Name: Activated, Class: BoolValue, Variable: I2ScrEOFActivatedEOF7005id7337 
	local I2ScrEOFActivatedEOF7005id7337 = Instance.new("BoolValue", I2ScrEOFConfigEOF6051id1965)
	I2ScrEOFActivatedEOF7005id7337.Name = "Activated"

	-- Time Taken: 0.09774140000001807s, Name: Action_Input, Class: Frame, Variable: I2ScrEOFAction_InputEOF9577id6436 
	local I2ScrEOFAction_InputEOF9577id6436 = Instance.new("Frame", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFAction_InputEOF9577id6436.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFAction_InputEOF9577id6436.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFAction_InputEOF9577id6436.BorderSizePixel = 0
	I2ScrEOFAction_InputEOF9577id6436.Name = "Action_Input"
	I2ScrEOFAction_InputEOF9577id6436.Position = UDim2.new(0.333333343, 0, 0.177358493, 0)
	I2ScrEOFAction_InputEOF9577id6436.Size = UDim2.new(0.949999988, 0, 0.0333333351, 0)

	-- Time Taken: 0.010834000000045307s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF8251id39 
	local I2ScrEOFUICornerEOF8251id39 = Instance.new("UICorner", I2ScrEOFAction_InputEOF9577id6436)
	I2ScrEOFUICornerEOF8251id39.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.22990189999984523s, Name: Description, Class: TextLabel, Variable: I2ScrEOFDescriptionEOF1879id960 
	local I2ScrEOFDescriptionEOF1879id960 = Instance.new("TextLabel", I2ScrEOFAction_InputEOF9577id6436)
	I2ScrEOFDescriptionEOF1879id960.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFDescriptionEOF1879id960.BackgroundTransparency = 1
	I2ScrEOFDescriptionEOF1879id960.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFDescriptionEOF1879id960.BorderSizePixel = 0
	I2ScrEOFDescriptionEOF1879id960.Name = "Description"
	I2ScrEOFDescriptionEOF1879id960.Position = UDim2.new(0.394267023, 0, 0.166666314, 0)
	I2ScrEOFDescriptionEOF1879id960.Size = UDim2.new(0.58468163, 0, 0.666666567, 0)
	I2ScrEOFDescriptionEOF1879id960.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFDescriptionEOF1879id960.Text = "Input"
	I2ScrEOFDescriptionEOF1879id960.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDescriptionEOF1879id960.TextScaled = true
	I2ScrEOFDescriptionEOF1879id960.TextSize = 14
	I2ScrEOFDescriptionEOF1879id960.TextStrokeTransparency = 0
	I2ScrEOFDescriptionEOF1879id960.TextWrapped = true
	I2ScrEOFDescriptionEOF1879id960.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.24164810000013404s, Name: Input, Class: TextBox, Variable: I2ScrEOFInputEOF7817id9159 
	local I2ScrEOFInputEOF7817id9159 = Instance.new("TextBox", I2ScrEOFAction_InputEOF9577id6436)
	I2ScrEOFInputEOF7817id9159.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFInputEOF7817id9159.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFInputEOF7817id9159.BorderSizePixel = 0
	I2ScrEOFInputEOF7817id9159.Name = "Input"
	I2ScrEOFInputEOF7817id9159.Position = UDim2.new(0.024575904, 0, 0.133116871, 0)
	I2ScrEOFInputEOF7817id9159.Size = UDim2.new(0.351084292, 0, 0.667060196, 0)
	I2ScrEOFInputEOF7817id9159.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFInputEOF7817id9159.PlaceholderText = "Input Text..."
	I2ScrEOFInputEOF7817id9159.Text = ""
	I2ScrEOFInputEOF7817id9159.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFInputEOF7817id9159.TextScaled = true
	I2ScrEOFInputEOF7817id9159.TextSize = 14
	I2ScrEOFInputEOF7817id9159.TextStrokeTransparency = 0
	I2ScrEOFInputEOF7817id9159.TextWrapped = true
	I2ScrEOFInputEOF7817id9159.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.014796100000012302s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF9883id6828 
	local I2ScrEOFUICornerEOF9883id6828 = Instance.new("UICorner", I2ScrEOFInputEOF7817id9159)
	I2ScrEOFUICornerEOF9883id6828.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.011034300000005715s, Name: Config, Class: Folder, Variable: I2ScrEOFConfigEOF9608id2899 
	local I2ScrEOFConfigEOF9608id2899 = Instance.new("Folder", I2ScrEOFAction_InputEOF9577id6436)
	I2ScrEOFConfigEOF9608id2899.Name = "Config"

	-- Time Taken: 0.009119599999962702s, Name: #ActInput, Class: StringValue, Variable: I2ScrEOF_ActInputEOF29id9846 
	local I2ScrEOF_ActInputEOF29id9846 = Instance.new("StringValue", I2ScrEOFConfigEOF9608id2899)
	I2ScrEOF_ActInputEOF29id9846.Name = "#ActInput"

	-- Time Taken: 0.09349559999998291s, Name: Action_Slider, Class: Frame, Variable: I2ScrEOFAction_SliderEOF7195id5984 
	local I2ScrEOFAction_SliderEOF7195id5984 = Instance.new("Frame", I2ScrEOFKH_TemplateTabEOF6930id3449)
	I2ScrEOFAction_SliderEOF7195id5984.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFAction_SliderEOF7195id5984.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFAction_SliderEOF7195id5984.BorderSizePixel = 0
	I2ScrEOFAction_SliderEOF7195id5984.Name = "Action_Slider"
	I2ScrEOFAction_SliderEOF7195id5984.Position = UDim2.new(0.333333343, 0, 0.177358493, 0)
	I2ScrEOFAction_SliderEOF7195id5984.Size = UDim2.new(0.949999988, 0, 0.0333333351, 0)

	-- Time Taken: 0.007455599999957485s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF1524id6665 
	local I2ScrEOFUICornerEOF1524id6665 = Instance.new("UICorner", I2ScrEOFAction_SliderEOF7195id5984)
	I2ScrEOFUICornerEOF1524id6665.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.220265100000006s, Name: Description, Class: TextLabel, Variable: I2ScrEOFDescriptionEOF1355id1055 
	local I2ScrEOFDescriptionEOF1355id1055 = Instance.new("TextLabel", I2ScrEOFAction_SliderEOF7195id5984)
	I2ScrEOFDescriptionEOF1355id1055.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFDescriptionEOF1355id1055.BackgroundTransparency = 1
	I2ScrEOFDescriptionEOF1355id1055.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFDescriptionEOF1355id1055.BorderSizePixel = 0
	I2ScrEOFDescriptionEOF1355id1055.Name = "Description"
	I2ScrEOFDescriptionEOF1355id1055.Position = UDim2.new(0.459791481, 0, 0.166666314, 0)
	I2ScrEOFDescriptionEOF1355id1055.Size = UDim2.new(0.519156992, 0, 0.666666567, 0)
	I2ScrEOFDescriptionEOF1355id1055.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFDescriptionEOF1355id1055.Text = "Slider"
	I2ScrEOFDescriptionEOF1355id1055.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDescriptionEOF1355id1055.TextScaled = true
	I2ScrEOFDescriptionEOF1355id1055.TextSize = 14
	I2ScrEOFDescriptionEOF1355id1055.TextStrokeTransparency = 0
	I2ScrEOFDescriptionEOF1355id1055.TextWrapped = true
	I2ScrEOFDescriptionEOF1355id1055.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.014879500000006374s, Name: Config, Class: Folder, Variable: I2ScrEOFConfigEOF4390id6242 
	local I2ScrEOFConfigEOF4390id6242 = Instance.new("Folder", I2ScrEOFAction_SliderEOF7195id5984)
	I2ScrEOFConfigEOF4390id6242.Name = "Config"

	-- Time Taken: 0.0197081999999682s, Name: #ActSlider, Class: StringValue, Variable: I2ScrEOF_ActSliderEOF2182id3882 
	local I2ScrEOF_ActSliderEOF2182id3882 = Instance.new("StringValue", I2ScrEOFConfigEOF4390id6242)
	I2ScrEOF_ActSliderEOF2182id3882.Name = "#ActSlider"

	-- Time Taken: 0.007349300000100811s, Name: SlidePercentage, Class: NumberValue, Variable: I2ScrEOFSlidePercentageEOF6081id2214 
	local I2ScrEOFSlidePercentageEOF6081id2214 = Instance.new("NumberValue", I2ScrEOFConfigEOF4390id6242)
	I2ScrEOFSlidePercentageEOF6081id2214.Name = "SlidePercentage"

	-- Time Taken: 0.0252507999999807s, Name: SliderAmount, Class: NumberValue, Variable: I2ScrEOFSliderAmountEOF8236id8043 
	local I2ScrEOFSliderAmountEOF8236id8043 = Instance.new("NumberValue", I2ScrEOFConfigEOF4390id6242)
	I2ScrEOFSliderAmountEOF8236id8043.Name = "SliderAmount"

	-- Time Taken: 0.11778309999999692s, Name: SlideArea, Class: Frame, Variable: I2ScrEOFSlideAreaEOF3667id3425 
	local I2ScrEOFSlideAreaEOF3667id3425 = Instance.new("Frame", I2ScrEOFAction_SliderEOF7195id5984)
	I2ScrEOFSlideAreaEOF3667id3425.BackgroundColor3 = Color3.new(0, 1, 1)
	I2ScrEOFSlideAreaEOF3667id3425.BackgroundTransparency = 1
	I2ScrEOFSlideAreaEOF3667id3425.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFSlideAreaEOF3667id3425.BorderSizePixel = 0
	I2ScrEOFSlideAreaEOF3667id3425.Name = "SlideArea"
	I2ScrEOFSlideAreaEOF3667id3425.Position = UDim2.new(0.0249999706, 0, 0.132999808, 0)
	I2ScrEOFSlideAreaEOF3667id3425.Size = UDim2.new(0.265663385, 0, 0.666999996, 0)

	-- Time Taken: 0.10657880000007935s, Name: SlideBar, Class: Frame, Variable: I2ScrEOFSlideBarEOF8000id7729 
	local I2ScrEOFSlideBarEOF8000id7729 = Instance.new("Frame", I2ScrEOFSlideAreaEOF3667id3425)
	I2ScrEOFSlideBarEOF8000id7729.AnchorPoint = Vector2.new(0.5, 0.5)
	I2ScrEOFSlideBarEOF8000id7729.BackgroundColor3 = Color3.new(0, 0.478431, 0.478431)
	I2ScrEOFSlideBarEOF8000id7729.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFSlideBarEOF8000id7729.BorderSizePixel = 0
	I2ScrEOFSlideBarEOF8000id7729.Name = "SlideBar"
	I2ScrEOFSlideBarEOF8000id7729.Position = UDim2.new(0.5, 0, 0.5, 0)
	I2ScrEOFSlideBarEOF8000id7729.Size = UDim2.new(0.899999976, 0, 0.150000006, 0)

	-- Time Taken: 0.019063300000084382s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF8087id1462 
	local I2ScrEOFUICornerEOF8087id1462 = Instance.new("UICorner", I2ScrEOFSlideBarEOF8000id7729)
	I2ScrEOFUICornerEOF8087id1462.CornerRadius = UDim.new(1, 0)

	-- Time Taken: 0.09959979999996449s, Name: FillBar, Class: Frame, Variable: I2ScrEOFFillBarEOF1578id4479 
	local I2ScrEOFFillBarEOF1578id4479 = Instance.new("Frame", I2ScrEOFSlideAreaEOF3667id3425)
	I2ScrEOFFillBarEOF1578id4479.AnchorPoint = Vector2.new(0.5, 0.5)
	I2ScrEOFFillBarEOF1578id4479.BackgroundColor3 = Color3.new(0, 1, 1)
	I2ScrEOFFillBarEOF1578id4479.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFFillBarEOF1578id4479.BorderSizePixel = 0
	I2ScrEOFFillBarEOF1578id4479.Name = "FillBar"
	I2ScrEOFFillBarEOF1578id4479.Position = UDim2.new(0, 0, 0.5, 0)

	-- Time Taken: 0.007025799999951232s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF6880id5870 
	local I2ScrEOFUICornerEOF6880id5870 = Instance.new("UICorner", I2ScrEOFFillBarEOF1578id4479)
	I2ScrEOFUICornerEOF6880id5870.CornerRadius = UDim.new(1, 0)

	-- Time Taken: 0.17429479999987052s, Name: SlideButton, Class: TextButton, Variable: I2ScrEOFSlideButtonEOF4987id8053 
	local I2ScrEOFSlideButtonEOF4987id8053 = Instance.new("TextButton", I2ScrEOFSlideAreaEOF3667id3425)
	I2ScrEOFSlideButtonEOF4987id8053.AnchorPoint = Vector2.new(0.5, 0.5)
	I2ScrEOFSlideButtonEOF4987id8053.BackgroundColor3 = Color3.new(0, 1, 1)
	I2ScrEOFSlideButtonEOF4987id8053.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFSlideButtonEOF4987id8053.BorderSizePixel = 0
	I2ScrEOFSlideButtonEOF4987id8053.Name = "SlideButton"
	I2ScrEOFSlideButtonEOF4987id8053.Position = UDim2.new(0, 0, 0.5, 0)
	I2ScrEOFSlideButtonEOF4987id8053.Size = UDim2.new(0.131970271, 0, 0.499350637, 0)
	I2ScrEOFSlideButtonEOF4987id8053.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFSlideButtonEOF4987id8053.TextColor3 = Color3.new(0, 0, 0)
	I2ScrEOFSlideButtonEOF4987id8053.TextSize = 14
	I2ScrEOFSlideButtonEOF4987id8053.TextTransparency = 1

	-- Time Taken: 0.015434500000083062s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF5442id7263 
	local I2ScrEOFUICornerEOF5442id7263 = Instance.new("UICorner", I2ScrEOFSlideButtonEOF4987id8053)
	I2ScrEOFUICornerEOF5442id7263.CornerRadius = UDim.new(1, 0)

	-- Time Taken: 0.1787814999999s, Name: Input, Class: TextBox, Variable: I2ScrEOFInputEOF3124id2704 
	local I2ScrEOFInputEOF3124id2704 = Instance.new("TextBox", I2ScrEOFAction_SliderEOF7195id5984)
	I2ScrEOFInputEOF3124id2704.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFInputEOF3124id2704.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFInputEOF3124id2704.BorderSizePixel = 0
	I2ScrEOFInputEOF3124id2704.Name = "Input"
	I2ScrEOFInputEOF3124id2704.Position = UDim2.new(0.294910848, 0, 0.166469872, 0)
	I2ScrEOFInputEOF3124id2704.Size = UDim2.new(0.141565129, 0, 0.667060196, 0)
	I2ScrEOFInputEOF3124id2704.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFInputEOF3124id2704.PlaceholderText = "Input Number..."
	I2ScrEOFInputEOF3124id2704.Text = ""
	I2ScrEOFInputEOF3124id2704.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFInputEOF3124id2704.TextScaled = true
	I2ScrEOFInputEOF3124id2704.TextSize = 14
	I2ScrEOFInputEOF3124id2704.TextStrokeTransparency = 0
	I2ScrEOFInputEOF3124id2704.TextWrapped = true

	-- Time Taken: 0.004732600000011189s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF7509id5079 
	local I2ScrEOFUICornerEOF7509id5079 = Instance.new("UICorner", I2ScrEOFInputEOF3124id2704)
	I2ScrEOFUICornerEOF7509id5079.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.17867370000010396s, Name: Title, Class: TextLabel, Variable: I2ScrEOFTitleEOF8745id3914 
	local I2ScrEOFTitleEOF8745id3914 = Instance.new("TextLabel", I2ScrEOFMainEOF4084id4498)
	I2ScrEOFTitleEOF8745id3914.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFTitleEOF8745id3914.BackgroundTransparency = 1
	I2ScrEOFTitleEOF8745id3914.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTitleEOF8745id3914.BorderSizePixel = 0
	I2ScrEOFTitleEOF8745id3914.Name = "Title"
	I2ScrEOFTitleEOF8745id3914.Position = UDim2.new(0.0241715498, 0, 0.0226021316, 0)
	I2ScrEOFTitleEOF8745id3914.Size = UDim2.new(0.277777791, 0, 0.0666666701, 0)
	I2ScrEOFTitleEOF8745id3914.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFTitleEOF8745id3914.RichText = true
	I2ScrEOFTitleEOF8745id3914.Text = "KHLib UI"
	I2ScrEOFTitleEOF8745id3914.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFTitleEOF8745id3914.TextScaled = true
	I2ScrEOFTitleEOF8745id3914.TextSize = 14
	I2ScrEOFTitleEOF8745id3914.TextWrapped = true
	I2ScrEOFTitleEOF8745id3914.TextXAlignment = Enum.TextXAlignment.Left

	-- Time Taken: 0.19677290000004177s, Name: TabSelection, Class: ScrollingFrame, Variable: I2ScrEOFTabSelectionEOF6364id3511 
	local I2ScrEOFTabSelectionEOF6364id3511 = Instance.new("ScrollingFrame", I2ScrEOFMainEOF4084id4498)
	I2ScrEOFTabSelectionEOF6364id3511.Active = true
	I2ScrEOFTabSelectionEOF6364id3511.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFTabSelectionEOF6364id3511.BackgroundTransparency = 1
	I2ScrEOFTabSelectionEOF6364id3511.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFTabSelectionEOF6364id3511.BorderSizePixel = 0
	I2ScrEOFTabSelectionEOF6364id3511.Name = "TabSelection"
	I2ScrEOFTabSelectionEOF6364id3511.Position = UDim2.new(0, 0, 0.116999999, 0)
	I2ScrEOFTabSelectionEOF6364id3511.Size = UDim2.new(0.333333343, 0, 0.883333325, 0)
	I2ScrEOFTabSelectionEOF6364id3511.BottomImage = "http://www.roblox.com/asset/?id=10995799876"
	I2ScrEOFTabSelectionEOF6364id3511.CanvasSize = UDim2.new(0, 0, 3, 0)
	I2ScrEOFTabSelectionEOF6364id3511.MidImage = "http://www.roblox.com/asset/?id=10995799876"
	I2ScrEOFTabSelectionEOF6364id3511.ScrollBarImageColor3 = Color3.new(0.490196, 0.490196, 0.490196)
	I2ScrEOFTabSelectionEOF6364id3511.ScrollBarThickness = 2
	I2ScrEOFTabSelectionEOF6364id3511.TopImage = "http://www.roblox.com/asset/?id=10995799876"

	-- Time Taken: 0.008304399999929046s, Name: UIListLayout, Class: UIListLayout, Variable: I2ScrEOFUIListLayoutEOF5634id7486 
	local I2ScrEOFUIListLayoutEOF5634id7486 = Instance.new("UIListLayout", I2ScrEOFTabSelectionEOF6364id3511)
	I2ScrEOFUIListLayoutEOF5634id7486.SortOrder = Enum.SortOrder.LayoutOrder

	-- Time Taken: 0.009386099999915132s, Name: UIAspectRatioConstraint, Class: UIAspectRatioConstraint, Variable: I2ScrEOFUIAspectRatioConstraintEOF760id6916 
	local I2ScrEOFUIAspectRatioConstraintEOF760id6916 = Instance.new("UIAspectRatioConstraint", I2ScrEOFMainEOF4084id4498)
	I2ScrEOFUIAspectRatioConstraintEOF760id6916.AspectRatio = 1.5

	-- Time Taken: 0.08250360000010915s, Name: DragArea, Class: Frame, Variable: I2ScrEOFDragAreaEOF6093id5586 
	local I2ScrEOFDragAreaEOF6093id5586 = Instance.new("Frame", I2ScrEOFMainEOF4084id4498)
	I2ScrEOFDragAreaEOF6093id5586.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFDragAreaEOF6093id5586.BackgroundTransparency = 1
	I2ScrEOFDragAreaEOF6093id5586.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFDragAreaEOF6093id5586.BorderSizePixel = 0
	I2ScrEOFDragAreaEOF6093id5586.Name = "DragArea"
	I2ScrEOFDragAreaEOF6093id5586.Size = UDim2.new(1, 0, 0.116999999, 0)

	-- Time Taken: 0.17453480000006039s, Name: ButtonActivation, Class: TextButton, Variable: I2ScrEOFButtonActivationEOF7597id3418 
	local I2ScrEOFButtonActivationEOF7597id3418 = Instance.new("TextButton", I2ScrEOFKHLibUIEOF5672id2561)
	I2ScrEOFButtonActivationEOF7597id3418.BackgroundColor3 = Color3.new(0, 0, 0)
	I2ScrEOFButtonActivationEOF7597id3418.BackgroundTransparency = 0.800000011920929
	I2ScrEOFButtonActivationEOF7597id3418.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFButtonActivationEOF7597id3418.BorderSizePixel = 0
	I2ScrEOFButtonActivationEOF7597id3418.Name = "ButtonActivation"
	I2ScrEOFButtonActivationEOF7597id3418.Position = UDim2.new(0.486000001, 0, 0.0350000001, 0)
	I2ScrEOFButtonActivationEOF7597id3418.Size = UDim2.new(0.02734375, 0, 0.0486787222, 0)
	I2ScrEOFButtonActivationEOF7597id3418.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFButtonActivationEOF7597id3418.TextColor3 = Color3.new(0, 0, 0)
	I2ScrEOFButtonActivationEOF7597id3418.TextSize = 14
	I2ScrEOFButtonActivationEOF7597id3418.TextTransparency = 1

	-- Time Taken: 0s, Name: UIAspectRatioConstraint, Class: UIAspectRatioConstraint, Variable: I2ScrEOFUIAspectRatioConstraintEOF7798id6664 
	local I2ScrEOFUIAspectRatioConstraintEOF7798id6664 = Instance.new("UIAspectRatioConstraint", I2ScrEOFButtonActivationEOF7597id3418)

	-- Time Taken: 0.023148800000058145s, Name: UIStroke, Class: UIStroke, Variable: I2ScrEOFUIStrokeEOF3619id4497 
	local I2ScrEOFUIStrokeEOF3619id4497 = Instance.new("UIStroke", I2ScrEOFButtonActivationEOF7597id3418)
	I2ScrEOFUIStrokeEOF3619id4497.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
	I2ScrEOFUIStrokeEOF3619id4497.Thickness = 1.5

	-- Time Taken: 0.02049329999999827s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF8175id4823 
	local I2ScrEOFUICornerEOF8175id4823 = Instance.new("UICorner", I2ScrEOFButtonActivationEOF7597id3418)
	I2ScrEOFUICornerEOF8175id4823.CornerRadius = UDim.new(0.300000012, 0)

	-- Time Taken: 0.10713979999968615s, Name: ImageLabel, Class: ImageLabel, Variable: I2ScrEOFImageLabelEOF6602id1261 
	local I2ScrEOFImageLabelEOF6602id1261 = Instance.new("ImageLabel", I2ScrEOFButtonActivationEOF7597id3418)
	I2ScrEOFImageLabelEOF6602id1261.AnchorPoint = Vector2.new(0.5, 0.5)
	I2ScrEOFImageLabelEOF6602id1261.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFImageLabelEOF6602id1261.BackgroundTransparency = 1
	I2ScrEOFImageLabelEOF6602id1261.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFImageLabelEOF6602id1261.BorderSizePixel = 0
	I2ScrEOFImageLabelEOF6602id1261.Position = UDim2.new(0.5, 0, 0.5, 0)
	I2ScrEOFImageLabelEOF6602id1261.Size = UDim2.new(0.899999976, 0, 0.899999976, 0)
	I2ScrEOFImageLabelEOF6602id1261.Image = "rbxassetid://15016878198"

	-- Time Taken: 0.1196381999999403s, Name: ColorPick, Class: Frame, Variable: I2ScrEOFColorPickEOF1937id1048 
	local I2ScrEOFColorPickEOF1937id1048 = Instance.new("Frame", I2ScrEOFKHLibUIEOF5672id2561)
	I2ScrEOFColorPickEOF1937id1048.AnchorPoint = Vector2.new(0.5, 0.5)
	I2ScrEOFColorPickEOF1937id1048.BackgroundColor3 = Color3.new(0.0588235, 0.0588235, 0.0588235)
	I2ScrEOFColorPickEOF1937id1048.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFColorPickEOF1937id1048.BorderSizePixel = 0
	I2ScrEOFColorPickEOF1937id1048.Name = "ColorPick"
	I2ScrEOFColorPickEOF1937id1048.Position = UDim2.new(0.5, 0, 0.5, 0)
	I2ScrEOFColorPickEOF1937id1048.Size = UDim2.new(0.25390625, 0, 0.347705156, 0)
	I2ScrEOFColorPickEOF1937id1048.Visible = false

	-- Time Taken: 0.019367200000033336s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF7400id4832 
	local I2ScrEOFUICornerEOF7400id4832 = Instance.new("UICorner", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFUICornerEOF7400id4832.CornerRadius = UDim.new(0.0500000007, 0)

	-- Time Taken: 0.07367299999975785s, Name: ValueArea, Class: Frame, Variable: I2ScrEOFValueAreaEOF6463id9046 
	local I2ScrEOFValueAreaEOF6463id9046 = Instance.new("Frame", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFValueAreaEOF6463id9046.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFValueAreaEOF6463id9046.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFValueAreaEOF6463id9046.BorderSizePixel = 0
	I2ScrEOFValueAreaEOF6463id9046.Name = "ValueArea"
	I2ScrEOFValueAreaEOF6463id9046.Position = UDim2.new(0.0338461548, 0, 0.899999976, 0)
	I2ScrEOFValueAreaEOF6463id9046.Size = UDim2.new(0.630769253, 0, 0.0599999987, 0)

	-- Time Taken: 0.018112599999994927s, Name: UIGradient, Class: UIGradient, Variable: I2ScrEOFUIGradientEOF4607id9914 
	local I2ScrEOFUIGradientEOF4607id9914 = Instance.new("UIGradient", I2ScrEOFValueAreaEOF6463id9046)
	 -- ColorSequence Not Supported; Skipped.

	-- Time Taken: 0.014684099999954014s, Name: UIStroke, Class: UIStroke, Variable: I2ScrEOFUIStrokeEOF9026id5544 
	local I2ScrEOFUIStrokeEOF9026id5544 = Instance.new("UIStroke", I2ScrEOFValueAreaEOF6463id9046)
	I2ScrEOFUIStrokeEOF9026id5544.Color = Color3.new(0.478431, 0.478431, 0.478431)

	-- Time Taken: 0.012454300000058538s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF9695id9154 
	local I2ScrEOFUICornerEOF9695id9154 = Instance.new("UICorner", I2ScrEOFValueAreaEOF6463id9046)
	I2ScrEOFUICornerEOF9695id9154.CornerRadius = UDim.new(1, 0)

	-- Time Taken: 0.07398279999995339s, Name: HueArea, Class: Frame, Variable: I2ScrEOFHueAreaEOF6313id3458 
	local I2ScrEOFHueAreaEOF6313id3458 = Instance.new("Frame", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFHueAreaEOF6313id3458.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFHueAreaEOF6313id3458.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFHueAreaEOF6313id3458.BorderSizePixel = 0
	I2ScrEOFHueAreaEOF6313id3458.Name = "HueArea"
	I2ScrEOFHueAreaEOF6313id3458.Position = UDim2.new(0.0338461548, 0, 0.0399999991, 0)
	I2ScrEOFHueAreaEOF6313id3458.Size = UDim2.new(0.630769253, 0, 0.819999993, 0)

	-- Time Taken: 0.010507999999958884s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF9376id1200 
	local I2ScrEOFUICornerEOF9376id1200 = Instance.new("UICorner", I2ScrEOFHueAreaEOF6313id3458)
	I2ScrEOFUICornerEOF9376id1200.CornerRadius = UDim.new(0.0500000007, 0)

	-- Time Taken: 0.005173000000013417s, Name: UIStroke, Class: UIStroke, Variable: I2ScrEOFUIStrokeEOF5041id4131 
	local I2ScrEOFUIStrokeEOF5041id4131 = Instance.new("UIStroke", I2ScrEOFHueAreaEOF6313id3458)
	I2ScrEOFUIStrokeEOF5041id4131.Color = Color3.new(0.478431, 0.478431, 0.478431)

	-- Time Taken: 0.006778699999927085s, Name: UIGradient, Class: UIGradient, Variable: I2ScrEOFUIGradientEOF4532id9720 
	local I2ScrEOFUIGradientEOF4532id9720 = Instance.new("UIGradient", I2ScrEOFHueAreaEOF6313id3458)
	 -- ColorSequence Not Supported; Skipped.

	-- Time Taken: 0.07293319999985215s, Name: WhiteArea, Class: Frame, Variable: I2ScrEOFWhiteAreaEOF858id3403 
	local I2ScrEOFWhiteAreaEOF858id3403 = Instance.new("Frame", I2ScrEOFHueAreaEOF6313id3458)
	I2ScrEOFWhiteAreaEOF858id3403.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFWhiteAreaEOF858id3403.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFWhiteAreaEOF858id3403.BorderSizePixel = 0
	I2ScrEOFWhiteAreaEOF858id3403.Name = "WhiteArea"
	I2ScrEOFWhiteAreaEOF858id3403.Size = UDim2.new(1, 0, 1, 0)

	-- Time Taken: 0.010235699999952885s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF8077id5361 
	local I2ScrEOFUICornerEOF8077id5361 = Instance.new("UICorner", I2ScrEOFWhiteAreaEOF858id3403)
	I2ScrEOFUICornerEOF8077id5361.CornerRadius = UDim.new(0.0500000007, 0)

	-- Time Taken: 0.029976599999940845s, Name: UIGradient, Class: UIGradient, Variable: I2ScrEOFUIGradientEOF2930id6791 
	local I2ScrEOFUIGradientEOF2930id6791 = Instance.new("UIGradient", I2ScrEOFWhiteAreaEOF858id3403)
	I2ScrEOFUIGradientEOF2930id6791.Rotation = -90
	-- Number Sequence Is Not Supported; Skipped.

	-- Time Taken: 0.22684650000007878s, Name: RedInput, Class: TextBox, Variable: I2ScrEOFRedInputEOF7701id294 
	local I2ScrEOFRedInputEOF7701id294 = Instance.new("TextBox", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFRedInputEOF7701id294.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFRedInputEOF7701id294.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFRedInputEOF7701id294.BorderSizePixel = 0
	I2ScrEOFRedInputEOF7701id294.Name = "RedInput"
	I2ScrEOFRedInputEOF7701id294.Position = UDim2.new(0.782165527, 0, 0.0399999991, 0)
	I2ScrEOFRedInputEOF7701id294.Size = UDim2.new(0.184615389, 0, 0.100000001, 0)
	I2ScrEOFRedInputEOF7701id294.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFRedInputEOF7701id294.PlaceholderColor3 = Color3.new(0.698039, 0, 0)
	I2ScrEOFRedInputEOF7701id294.PlaceholderText = "0-255..."
	I2ScrEOFRedInputEOF7701id294.Text = "255"
	I2ScrEOFRedInputEOF7701id294.TextColor3 = Color3.new(1, 0, 0)
	I2ScrEOFRedInputEOF7701id294.TextScaled = true
	I2ScrEOFRedInputEOF7701id294.TextSize = 14
	I2ScrEOFRedInputEOF7701id294.TextStrokeTransparency = 0
	I2ScrEOFRedInputEOF7701id294.TextWrapped = true

	-- Time Taken: 0.013022899999896254s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF1431id8743 
	local I2ScrEOFUICornerEOF1431id8743 = Instance.new("UICorner", I2ScrEOFRedInputEOF7701id294)
	I2ScrEOFUICornerEOF1431id8743.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.20437749999996413s, Name: Label, Class: TextLabel, Variable: I2ScrEOFLabelEOF8121id5355 
	local I2ScrEOFLabelEOF8121id5355 = Instance.new("TextLabel", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFLabelEOF8121id5355.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFLabelEOF8121id5355.BackgroundTransparency = 1
	I2ScrEOFLabelEOF8121id5355.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFLabelEOF8121id5355.BorderSizePixel = 0
	I2ScrEOFLabelEOF8121id5355.Name = "Label"
	I2ScrEOFLabelEOF8121id5355.Position = UDim2.new(0.702938318, 0, 0.0399999991, 0)
	I2ScrEOFLabelEOF8121id5355.Size = UDim2.new(0.0769230798, 0, 0.100000001, 0)
	I2ScrEOFLabelEOF8121id5355.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFLabelEOF8121id5355.Text = "R"
	I2ScrEOFLabelEOF8121id5355.TextColor3 = Color3.new(1, 0, 0)
	I2ScrEOFLabelEOF8121id5355.TextScaled = true
	I2ScrEOFLabelEOF8121id5355.TextSize = 14
	I2ScrEOFLabelEOF8121id5355.TextStrokeTransparency = 0
	I2ScrEOFLabelEOF8121id5355.TextWrapped = true

	-- Time Taken: 0.18881230000010873s, Name: Label, Class: TextLabel, Variable: I2ScrEOFLabelEOF6343id1656 
	local I2ScrEOFLabelEOF6343id1656 = Instance.new("TextLabel", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFLabelEOF6343id1656.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFLabelEOF6343id1656.BackgroundTransparency = 1
	I2ScrEOFLabelEOF6343id1656.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFLabelEOF6343id1656.BorderSizePixel = 0
	I2ScrEOFLabelEOF6343id1656.Name = "Label"
	I2ScrEOFLabelEOF6343id1656.Position = UDim2.new(0.702938318, 0, 0.180000007, 0)
	I2ScrEOFLabelEOF6343id1656.Size = UDim2.new(0.0769230798, 0, 0.100000001, 0)
	I2ScrEOFLabelEOF6343id1656.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFLabelEOF6343id1656.Text = "G"
	I2ScrEOFLabelEOF6343id1656.TextColor3 = Color3.new(0, 1, 0)
	I2ScrEOFLabelEOF6343id1656.TextScaled = true
	I2ScrEOFLabelEOF6343id1656.TextSize = 14
	I2ScrEOFLabelEOF6343id1656.TextStrokeTransparency = 0
	I2ScrEOFLabelEOF6343id1656.TextWrapped = true

	-- Time Taken: 0.1855079999999134s, Name: Label, Class: TextLabel, Variable: I2ScrEOFLabelEOF8064id6284 
	local I2ScrEOFLabelEOF8064id6284 = Instance.new("TextLabel", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFLabelEOF8064id6284.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFLabelEOF8064id6284.BackgroundTransparency = 1
	I2ScrEOFLabelEOF8064id6284.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFLabelEOF8064id6284.BorderSizePixel = 0
	I2ScrEOFLabelEOF8064id6284.Name = "Label"
	I2ScrEOFLabelEOF8064id6284.Position = UDim2.new(0.702938318, 0, 0.319999993, 0)
	I2ScrEOFLabelEOF8064id6284.Size = UDim2.new(0.0769230798, 0, 0.100000001, 0)
	I2ScrEOFLabelEOF8064id6284.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFLabelEOF8064id6284.Text = "B"
	I2ScrEOFLabelEOF8064id6284.TextColor3 = Color3.new(0, 0, 1)
	I2ScrEOFLabelEOF8064id6284.TextScaled = true
	I2ScrEOFLabelEOF8064id6284.TextSize = 14
	I2ScrEOFLabelEOF8064id6284.TextStrokeTransparency = 0
	I2ScrEOFLabelEOF8064id6284.TextWrapped = true

	-- Time Taken: 0.19830469999976685s, Name: BlueInput, Class: TextBox, Variable: I2ScrEOFBlueInputEOF251id4344 
	local I2ScrEOFBlueInputEOF251id4344 = Instance.new("TextBox", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFBlueInputEOF251id4344.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFBlueInputEOF251id4344.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFBlueInputEOF251id4344.BorderSizePixel = 0
	I2ScrEOFBlueInputEOF251id4344.Name = "BlueInput"
	I2ScrEOFBlueInputEOF251id4344.Position = UDim2.new(0.782165527, 0, 0.319999993, 0)
	I2ScrEOFBlueInputEOF251id4344.Size = UDim2.new(0.184615389, 0, 0.100000001, 0)
	I2ScrEOFBlueInputEOF251id4344.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFBlueInputEOF251id4344.PlaceholderColor3 = Color3.new(0, 0, 0.698039)
	I2ScrEOFBlueInputEOF251id4344.PlaceholderText = "0-255..."
	I2ScrEOFBlueInputEOF251id4344.Text = "255"
	I2ScrEOFBlueInputEOF251id4344.TextColor3 = Color3.new(0, 0, 1)
	I2ScrEOFBlueInputEOF251id4344.TextScaled = true
	I2ScrEOFBlueInputEOF251id4344.TextSize = 14
	I2ScrEOFBlueInputEOF251id4344.TextStrokeTransparency = 0
	I2ScrEOFBlueInputEOF251id4344.TextWrapped = true

	-- Time Taken: 0.014581900000052883s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF3062id9731 
	local I2ScrEOFUICornerEOF3062id9731 = Instance.new("UICorner", I2ScrEOFBlueInputEOF251id4344)
	I2ScrEOFUICornerEOF3062id9731.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.19299130000001696s, Name: GreenInput, Class: TextBox, Variable: I2ScrEOFGreenInputEOF1469id3203 
	local I2ScrEOFGreenInputEOF1469id3203 = Instance.new("TextBox", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFGreenInputEOF1469id3203.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFGreenInputEOF1469id3203.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFGreenInputEOF1469id3203.BorderSizePixel = 0
	I2ScrEOFGreenInputEOF1469id3203.Name = "GreenInput"
	I2ScrEOFGreenInputEOF1469id3203.Position = UDim2.new(0.782165527, 0, 0.180000007, 0)
	I2ScrEOFGreenInputEOF1469id3203.Size = UDim2.new(0.184615389, 0, 0.100000001, 0)
	I2ScrEOFGreenInputEOF1469id3203.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFGreenInputEOF1469id3203.PlaceholderColor3 = Color3.new(0, 0.698039, 0)
	I2ScrEOFGreenInputEOF1469id3203.PlaceholderText = "0-255..."
	I2ScrEOFGreenInputEOF1469id3203.Text = "255"
	I2ScrEOFGreenInputEOF1469id3203.TextColor3 = Color3.new(0, 1, 0)
	I2ScrEOFGreenInputEOF1469id3203.TextScaled = true
	I2ScrEOFGreenInputEOF1469id3203.TextSize = 14
	I2ScrEOFGreenInputEOF1469id3203.TextStrokeTransparency = 0
	I2ScrEOFGreenInputEOF1469id3203.TextWrapped = true

	-- Time Taken: 0.0053672999999889726s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF6047id1085 
	local I2ScrEOFUICornerEOF6047id1085 = Instance.new("UICorner", I2ScrEOFGreenInputEOF1469id3203)
	I2ScrEOFUICornerEOF6047id1085.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.2103728999999248s, Name: HexInput, Class: TextBox, Variable: I2ScrEOFHexInputEOF3482id2178 
	local I2ScrEOFHexInputEOF3482id2178 = Instance.new("TextBox", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFHexInputEOF3482id2178.BackgroundColor3 = Color3.new(0.0980392, 0.0980392, 0.0980392)
	I2ScrEOFHexInputEOF3482id2178.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFHexInputEOF3482id2178.BorderSizePixel = 0
	I2ScrEOFHexInputEOF3482id2178.Name = "HexInput"
	I2ScrEOFHexInputEOF3482id2178.Position = UDim2.new(0.779088616, 0, 0.547999978, 0)
	I2ScrEOFHexInputEOF3482id2178.Size = UDim2.new(0.184615389, 0, 0.100000001, 0)
	I2ScrEOFHexInputEOF3482id2178.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFHexInputEOF3482id2178.PlaceholderColor3 = Color3.new(0.698039, 0.698039, 0.698039)
	I2ScrEOFHexInputEOF3482id2178.PlaceholderText = "#000000-#FFFFFF"
	I2ScrEOFHexInputEOF3482id2178.Text = ""
	I2ScrEOFHexInputEOF3482id2178.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFHexInputEOF3482id2178.TextScaled = true
	I2ScrEOFHexInputEOF3482id2178.TextSize = 14
	I2ScrEOFHexInputEOF3482id2178.TextStrokeTransparency = 0
	I2ScrEOFHexInputEOF3482id2178.TextWrapped = true

	-- Time Taken: 0.006132600000000821s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF2491id2402 
	local I2ScrEOFUICornerEOF2491id2402 = Instance.new("UICorner", I2ScrEOFHexInputEOF3482id2178)
	I2ScrEOFUICornerEOF2491id2402.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.1742802000002257s, Name: Label, Class: TextLabel, Variable: I2ScrEOFLabelEOF6430id7215 
	local I2ScrEOFLabelEOF6430id7215 = Instance.new("TextLabel", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFLabelEOF6430id7215.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFLabelEOF6430id7215.BackgroundTransparency = 1
	I2ScrEOFLabelEOF6430id7215.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFLabelEOF6430id7215.BorderSizePixel = 0
	I2ScrEOFLabelEOF6430id7215.Name = "Label"
	I2ScrEOFLabelEOF6430id7215.Position = UDim2.new(0.702938318, 0, 0.547999978, 0)
	I2ScrEOFLabelEOF6430id7215.Size = UDim2.new(0.0769230798, 0, 0.100000001, 0)
	I2ScrEOFLabelEOF6430id7215.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFLabelEOF6430id7215.Text = "H"
	I2ScrEOFLabelEOF6430id7215.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFLabelEOF6430id7215.TextScaled = true
	I2ScrEOFLabelEOF6430id7215.TextSize = 14
	I2ScrEOFLabelEOF6430id7215.TextStrokeTransparency = 0
	I2ScrEOFLabelEOF6430id7215.TextWrapped = true

	-- Time Taken: 0.0041602000000011685s, Name: UIAspectRatioConstraint, Class: UIAspectRatioConstraint, Variable: I2ScrEOFUIAspectRatioConstraintEOF7068id4332 
	local I2ScrEOFUIAspectRatioConstraintEOF7068id4332 = Instance.new("UIAspectRatioConstraint", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFUIAspectRatioConstraintEOF7068id4332.AspectRatio = 1.2999999523162842

	-- Time Taken: 0.1727168999997275s, Name: Submit, Class: TextButton, Variable: I2ScrEOFSubmitEOF4802id9320 
	local I2ScrEOFSubmitEOF4802id9320 = Instance.new("TextButton", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFSubmitEOF4802id9320.BackgroundColor3 = Color3.new(0.333333, 1, 0.498039)
	I2ScrEOFSubmitEOF4802id9320.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFSubmitEOF4802id9320.BorderSizePixel = 0
	I2ScrEOFSubmitEOF4802id9320.Name = "Submit"
	I2ScrEOFSubmitEOF4802id9320.Position = UDim2.new(0.702938259, 0, 0.858824253, 0)
	I2ScrEOFSubmitEOF4802id9320.Size = UDim2.new(0.260512829, 0, 0.0986666679, 0)
	I2ScrEOFSubmitEOF4802id9320.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFSubmitEOF4802id9320.Text = "Submit"
	I2ScrEOFSubmitEOF4802id9320.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFSubmitEOF4802id9320.TextScaled = true
	I2ScrEOFSubmitEOF4802id9320.TextSize = 14
	I2ScrEOFSubmitEOF4802id9320.TextStrokeTransparency = 0
	I2ScrEOFSubmitEOF4802id9320.TextWrapped = true

	-- Time Taken: 0.013446199999975761s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF6982id7425 
	local I2ScrEOFUICornerEOF6982id7425 = Instance.new("UICorner", I2ScrEOFSubmitEOF4802id9320)
	I2ScrEOFUICornerEOF6982id7425.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.034226300000000265s, Name: UIStroke, Class: UIStroke, Variable: I2ScrEOFUIStrokeEOF4474id9360 
	local I2ScrEOFUIStrokeEOF4474id9360 = Instance.new("UIStroke", I2ScrEOFSubmitEOF4802id9320)
	I2ScrEOFUIStrokeEOF4474id9360.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
	I2ScrEOFUIStrokeEOF4474id9360.Color = Color3.new(0.478431, 0.478431, 0.478431)
	I2ScrEOFUIStrokeEOF4474id9360.Thickness = 2

	-- Time Taken: 0.1622463000002199s, Name: Cancel, Class: TextButton, Variable: I2ScrEOFCancelEOF3996id7911 
	local I2ScrEOFCancelEOF3996id7911 = Instance.new("TextButton", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFCancelEOF3996id7911.BackgroundColor3 = Color3.new(1, 0.34902, 0.34902)
	I2ScrEOFCancelEOF3996id7911.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFCancelEOF3996id7911.BorderSizePixel = 0
	I2ScrEOFCancelEOF3996id7911.Name = "Cancel"
	I2ScrEOFCancelEOF3996id7911.Position = UDim2.new(0.702938259, 0, 0.733425617, 0)
	I2ScrEOFCancelEOF3996id7911.Size = UDim2.new(0.260512829, 0, 0.0986666679, 0)
	I2ScrEOFCancelEOF3996id7911.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	I2ScrEOFCancelEOF3996id7911.Text = "Cancel"
	I2ScrEOFCancelEOF3996id7911.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFCancelEOF3996id7911.TextScaled = true
	I2ScrEOFCancelEOF3996id7911.TextSize = 14
	I2ScrEOFCancelEOF3996id7911.TextStrokeTransparency = 0
	I2ScrEOFCancelEOF3996id7911.TextWrapped = true

	-- Time Taken: 0.006735100000014427s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF7584id4500 
	local I2ScrEOFUICornerEOF7584id4500 = Instance.new("UICorner", I2ScrEOFCancelEOF3996id7911)
	I2ScrEOFUICornerEOF7584id4500.CornerRadius = UDim.new(0.200000003, 0)

	-- Time Taken: 0.039165599999932965s, Name: UIStroke, Class: UIStroke, Variable: I2ScrEOFUIStrokeEOF9855id9441 
	local I2ScrEOFUIStrokeEOF9855id9441 = Instance.new("UIStroke", I2ScrEOFCancelEOF3996id7911)
	I2ScrEOFUIStrokeEOF9855id9441.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
	I2ScrEOFUIStrokeEOF9855id9441.Color = Color3.new(0.478431, 0.478431, 0.478431)
	I2ScrEOFUIStrokeEOF9855id9441.Thickness = 2

	-- Time Taken: 0.0719146000001274s, Name: ColorVisual, Class: Frame, Variable: I2ScrEOFColorVisualEOF1871id2557 
	local I2ScrEOFColorVisualEOF1871id2557 = Instance.new("Frame", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFColorVisualEOF1871id2557.BackgroundColor3 = Color3.new(1, 1, 1)
	I2ScrEOFColorVisualEOF1871id2557.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFColorVisualEOF1871id2557.BorderSizePixel = 0
	I2ScrEOFColorVisualEOF1871id2557.Name = "ColorVisual"
	I2ScrEOFColorVisualEOF1871id2557.Position = UDim2.new(0.702086985, 0, 0.447098166, 0)
	I2ScrEOFColorVisualEOF1871id2557.Size = UDim2.new(0.261364132, 0, 0.0760103092, 0)

	-- Time Taken: 0.01368420000005699s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF8324id4173 
	local I2ScrEOFUICornerEOF8324id4173 = Instance.new("UICorner", I2ScrEOFColorVisualEOF1871id2557)
	I2ScrEOFUICornerEOF8324id4173.CornerRadius = UDim.new(0.25, 0)

	-- Time Taken: 0.005387400000017806s, Name: UIStroke, Class: UIStroke, Variable: I2ScrEOFUIStrokeEOF7929id8268 
	local I2ScrEOFUIStrokeEOF7929id8268 = Instance.new("UIStroke", I2ScrEOFColorVisualEOF1871id2557)
	I2ScrEOFUIStrokeEOF7929id8268.Color = Color3.new(0.478431, 0.478431, 0.478431)

	-- Time Taken: 0.1504051999999092s, Name: Lock, Class: TextLabel, Variable: I2ScrEOFLockEOF9041id8740 
	local I2ScrEOFLockEOF9041id8740 = Instance.new("TextLabel", I2ScrEOFColorPickEOF1937id1048)
	I2ScrEOFLockEOF9041id8740.BackgroundColor3 = Color3.new(0.329412, 0, 0)
	I2ScrEOFLockEOF9041id8740.BorderColor3 = Color3.new(0, 0, 0)
	I2ScrEOFLockEOF9041id8740.BorderSizePixel = 0
	I2ScrEOFLockEOF9041id8740.Name = "Lock"
	I2ScrEOFLockEOF9041id8740.Position = UDim2.new(0.0338461585, 0, 0.0399999395, 0)
	I2ScrEOFLockEOF9041id8740.Size = UDim2.new(0, 205, 0, 229)
	I2ScrEOFLockEOF9041id8740.FontFace = Font.new("rbxasset://fonts/families/Roboto.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
	I2ScrEOFLockEOF9041id8740.Text = "The color picker is still in work in progress. We're updating it soon to have a color picker instead of typing the color code in."
	I2ScrEOFLockEOF9041id8740.TextColor3 = Color3.new(1, 1, 1)
	I2ScrEOFLockEOF9041id8740.TextScaled = true
	I2ScrEOFLockEOF9041id8740.TextSize = 14
	I2ScrEOFLockEOF9041id8740.TextWrapped = true

	-- Time Taken: 0.020268500000042877s, Name: UICorner, Class: UICorner, Variable: I2ScrEOFUICornerEOF3929id8983 
	local I2ScrEOFUICornerEOF3929id8983 = Instance.new("UICorner", I2ScrEOFLockEOF9041id8740)
	I2ScrEOFUICornerEOF3929id8983.CornerRadius = UDim.new(0.0500000007, 0)

	-- Time Taken: 0.025280599999973674s, Name: UIStroke, Class: UIStroke, Variable: I2ScrEOFUIStrokeEOF1956id8280 
	local I2ScrEOFUIStrokeEOF1956id8280 = Instance.new("UIStroke", I2ScrEOFLockEOF9041id8740)
	I2ScrEOFUIStrokeEOF1956id8280.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
	I2ScrEOFUIStrokeEOF1956id8280.Thickness = 3
end

return I2ScrBuilder
